# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_money', models.IntegerField(unique=True)),
                ('grade_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stu_infor',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20, unique=True)),
                ('stu_password', models.IntegerField()),
                ('stu_grade_id', models.IntegerField()),
            ],
        ),
    ]
